name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: "7"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Crypto.dll"
changelog: |2-
  ### New features and improvements ###
  - Add tagline as available parameter (#68) @crobibero
  - Add Form Post support (#65) @crobibero

  ### Bug Fixes ###
  - Fix Discord.handlebars template (#66) @crobibero
  - Fix string conversion for unbound properties (#62) @crobibero
