name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: "5"
targetAbi: "10.7.7.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Crypto.dll"
changelog: |2-
  ### Bug Fixes ###
  - Update Username parameter to be NotificationUsername (#57) @crobibero

  ### CI & build changes ###
  - ci: set ABI version and more repo automation (#52) @h1dden-da3m0n
